{% set name = "django-rdkit" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rdkit/django-rdkit/archive/v{{ version }}.tar.gz
  sha256: caa4394b858a02f88a526dc0c029d3500085f1756e4d465ecdb7733dac6814e9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3

test:
  imports:
    - django_rdkit

about:
  home: https://github.com/rdkit/django-rdkit
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A Django extension to easily use RDKit functionalities
  description: |
    django-rdkit offers models for molecules that makes it very easy to create chemically-aware django applications
  doc_url: https://django-rdkit.readthedocs.io
  dev_url: https://github.com/rdkit/django-rdkit

extra:
  recipe-maintainers:
    - roukydesbois
