{% set name = "django-rdkit" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rdkit/django-rdkit/archive/v{{ version }}.tar.gz
  sha256: 4c507274b41c4759c2f345d43854c0eafeb5ecfe877299b7481975f6cf22f6a7

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3

test:
  imports:
    - django_rdkit

about:
  home: https://github.com/rdkit/django-rdkit
  license:  BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A Django extension to easily use RDKit functionalities'
  description: |
    django-rdkit offers models for molecules that makes it very easy to create chemically-aware django applications
  doc_url: https://django-rdkit.readthedocs.io
  dev_url: https://github.com/rdkit/django-rdkit

extra:
  recipe-maintainers:
    - roukydesbois
